[package]
name = "blockchain-sample"
version = "0.1.0"
authors = ["xuyizhe <barrenbass@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
blake3 = "0.3.7"
